name: PR Notification to Discord

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: peter-evans/discord-webhook-action@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "A new pull request has been created: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}."
